config/routes.rb
Rails.application.routes.draw do
  resources :data_pages
  get 'users/index'
  get 'users/login_check'
  devise_for :accounts
  resources :board_messages
  resources :board_users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
  belongs_to :board_user

  validates :content, presence: {message:"は、必須項目です。"}

end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :account
  has_many :board_messsage

  validates :nickname, presence: {message:"は、必須項目です。"}
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController
  before_action :set_board_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  layout 'board_messages'

  def index
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    users = BoardUser.where('account_id == ?', current_account.id)[0]
    if users == nil then
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users = BoardUser.where 'account_id == ?', current_account.id
    end
    @board_user = users
    @board_message = BoardMessage.new
    @board_message.board_user_id = @board_user.id
  end

  def show
    redirect_to '/board_messages'
  end

  def new
    redirect_to '/board_messages'
  end

  def edit
    redirect_to '/board_messages'
  end

  def create
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    @board_message = BoardMessage.new(board_message_params)
    @board_user = BoardUser.where('account_id == ?', current_account.id)[0]
    respond_to do |format|
      if @board_message.save
        format.html { redirect_to '/board_messages' }
        format.json { render :show, status: :created, location: @board_message }
      else
        format.html { render :index }
        format.json { render json: @board_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    redirect_to '/board_messages'
  end

  def destroy
    redirect_to '/board_messages'
  end

  private
  def set_board_message
    @board_message = BoardMessage.find(params[:id])
  end

  def board_message_params
    params.require(:board_message).permit(:content, :board_user_id)
  end
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
before_action :set_board_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  # layout 'board_users' # 必要に応じて用意

  def index
    users = BoardUser.where 'account_id == ?',
        current_account.id
    if users[0] == nil then
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users = BoardUser.where 'account_id == ?',
          current_account.id
    end
    @board_user = users[0]
  end

  def show
    @board_user = BoardUser.find params[:id]
  end

  def new
    redirect_to '/board_messages'
  end

  def edit
    redirect_to '/board_messages'
  end

  def create
    redirect_to '/board_messages'
  end

  def update
    respond_to do |format|
      if @board_user.update(board_user_params)
        format.html { redirect_to '/board_messages' }
        format.json { render :show, status: :ok,
            location: @board_user }
      else
        format.html { render :index }
        format.json { render json: @board_user.errors,
            status: :unprocessable_entity }
      end
    end
  end

  def destroy
    redirect_to '/board_messages'
  end

  private
  def set_board_user
    @board_user = BoardUser.find(params[:id])
  end

  def board_user_params
    params.require(:board_user).permit(:nickname, :account_id, :memo)
  end
end

app/controllers/data_pages_controller.rb
class DataPagesController < ApplicationController
  before_action :set_data_page, only: %i[ show edit update destroy ]

  # GET /data_pages or /data_pages.json
  def index
    @data_pages = DataPage.page params[:page]
  end

  # GET /data_pages/1 or /data_pages/1.json
  def show
  end

  # GET /data_pages/new
  def new
    @data_page = DataPage.new
  end

  # GET /data_pages/1/edit
  def edit
  end

  # POST /data_pages or /data_pages.json
  def create
    @data_page = DataPage.new(data_page_params)

    respond_to do |format|
      if @data_page.save
        format.html { redirect_to data_page_url(@data_page), notice: "Data page was successfully created." }
        format.json { render :show, status: :created, location: @data_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_pages/1 or /data_pages/1.json
  def update
    respond_to do |format|
      if @data_page.update(data_page_params)
        format.html { redirect_to data_page_url(@data_page), notice: "Data page was successfully updated." }
        format.json { render :show, status: :ok, location: @data_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_pages/1 or /data_pages/1.json
  def destroy
    @data_page.destroy

    respond_to do |format|
      format.html { redirect_to data_pages_url, notice: "Data page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_page
      @data_page = DataPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_page_params
      params.require(:data_page).permit(:data)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  before_action :authenticate_account!, only: :login_check
 
  def index
    @msg = 'this is sample page.'
  end

  def login_check
    @account = current_account
    @msg = 'account created at: ' + @account.created_at.to_s
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

app/helpers/board_users_helper.rb
module BoardUsersHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/board_messages/_form.html.erb
<%= form_with(model: board_message, local: true) do |form| %>
  <% if board_message.errors.any? %>
    <div id="error_explanation">
      <h2 class="h4"><%= pluralize(board_message.errors.count, "error") %> 
          prohibited this board_message from being saved:</h2>
      <ul>
        <% board_message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :board_user_id %>
    <div class="border p-1">
      <%=@board_user.nickname %></div>
    <%= form.hidden_field :board_user_id %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_messages/edit.html.erb
<h1>Editing Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Show', @board_message %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_messages/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="display-4 text-primary">Message Board</h1>
<%= render 'form', board_message: @board_message %>
<p><%= link_to 'go home >>', controller: :board_users %></p>
<hr>
<h2 class="h4">※Posted Messages.</h2>
<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th width="200px">User</th>
     </tr>
  </thead>

  <tbody>
    <% @board_messages.each do |board_message| %>
      <tr>
        <td><%= board_message.content %></td>
        <td><%=link_to board_message.board_user.nickname,
            controller: :board_users, action: :show,
            id:board_message.board_user_id  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div><%= paginate @board_messages %></div>
<hr>
<div>copyright SYODA-Tuyano 2020.</div>

app/views/board_messages/new.html.erb
<h1>New Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Back', board_messages_path %>

app/views/board_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @board_message.content %>
</p>

<p>
  <strong>Board user:</strong>
  <%= @board_message.board_user_id %>
</p>

<%= link_to 'Edit', edit_board_message_path(@board_message) %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_users/_form.html.erb
<%= form_with(model: board_user, local: true) do |form| %>
  <% if board_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_user.errors.count, "error") %>
          prohibited this board_user from being saved:</h2>
      <ul>
        <% board_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :account_id %>

  <div class="form-group">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :account_id %>
    <div class="border p-1">
      <%=@board_user.account_id %></div>
    <%= form.hidden_field :account_id %>
  </div>

  <div class="form-group">
    <%= form.label :memo %>
    <%= form.text_area :memo, class:'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/board_users/edit.html.erb
<h1>Editing Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Show', @board_user %> |
<%= link_to 'Back', board_users_path %>

app/views/board_users/index.html.erb
<h1 class="display-4 text-primary">
  User Home</h1>
<h2 class="h4">※<%=@board_user.account.email %> さんの設定</h2>
<%= render 'form', board_user: @board_user %>
<hr>
<p><%=link_to '<< go back', controller: :board_messages %></p>

<hr>
<div>copyright SYODA-Tuyano 2020.</div>

app/views/board_users/new.html.erb
<h1>New Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Back', board_users_path %>

app/views/board_users/show.html.erb
<h1 class="display-4 text-primary">
  "<%=@board_user.nickname %>"</h1>
<table class="table">
  <tr>
    <th>Nickname</th>
    <td><%= @board_user.nickname %></td>
  </tr>
  <tr>
    <th>Id</th>
    <td><%= @board_user.id %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @board_user.created_at %></td>
  </tr>
  <tr>
    <th>Memo</th>
    <td><%= @board_user.memo %></td>
  </tr>
</table>

<hr>
<%= link_to '<< Back', controller: :board_messages %>
<hr>
<div>copyright SYODA-Tuyano 2020.</div>

app/views/data_pages/_form.html.erb
<%= form_with(model: data_page) do |form| %>
  <% if data_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_page.errors.count, "error") %> prohibited this data_page from being saved:</h2>

      <ul>
        <% data_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_pages/edit.html.erb
<h1>Editing Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Show', @data_page %> |
<%= link_to 'Back', data_pages_path %>

app/views/data_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Data Pages</h1>

<div class="mt-4 mb-4">
  <%= page_entries_info @data_pages %>
</div>

<table class="table">
<thead>
  <tr>
    <th>ID</th>
     <th>Data</th>
     <th>Created at</th>
     <th colspan="3"></th>
    </tr>
</thead>

<tbody>
<% @data_pages.each do |data_page| %>
  <tr>
    <td><%= data_page.id %></td>
    <td><%= data_page.data %></td>
    <td><%= data_page.created_at %></td>
    <td><%= link_to 'Show', data_page %></td>
    <td><%= link_to 'Edit', edit_data_page_path(data_page) %></td>
    <td><%= link_to 'Destroy', data_page, method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>
<br>
<div><%= paginate @data_pages %></div>
<br>
<%= link_to 'New Data Page', new_data_page_path %>

app/views/data_pages/new.html.erb
<h1>New Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Back', data_pages_path %>

app/views/data_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @data_page.data %>
</p>

<%= link_to 'Edit', edit_data_page_path(@data_page) %> |
<%= link_to 'Back', data_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDeviseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'application', media: 'all',
        'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
        'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/layouts/board_message.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board Messages</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'board_messages', media: 'all', 
      'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 
      'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
    <div class="mt-5 text-center small text-scondary border-top border-scondary">
    2020 SYODA-Tuyano.
  </div>
  </body>
</html>

app/views/users/index.html.erb
<h1 class="display-4 text-primary">
  Hello#index</h1>
<p><%= @msg %></p>
<hr>
<div><%=link_to 'login_check page!&gt;&gt;'.html_safe,
  {action:'login_check'} %></div>
<div><%= link_to "Sign out&gt;&gt;".html_safe,
  destroy_account_session_path, 
  method: :delete %></div>

app/views/users/login_check.html.erb
<h1 class="display-4 text-primary">
  <%= @account.email %></h1>
<p><%= @msg %></p>
<hr>
<div><%=link_to '&lt;&lt;go back'.html_safe,
  {action:'index'} %></div>